on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Luamdata actions
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Lumadata yaml test
        id: hello
        uses: Lumadata/actions@v0.2.0
        with:
          repository-key: ${{ secrets.REPOSITORY_KEY }}
          repository-secret-key: ${{ secrets.REPOSITORY_SECRET_KEY }}
          path-to-directory: tests